version: '3.8'

services:
  quiz-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9015:9015"
    restart: unless-stopped
    container_name: programming-quiz-app
    environment:
      - NODE_ENV=production

networks:
  default:
    name: quiz-network